name: 'task_w_01'
version: '1.0.0'

profile: 'muscle_training'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  task_w_01:
    +database: "MUSCLE_DB_TASK_W_01"
    +schema: "DBT_PJT"
    +materialized: "view"
    mart:
      +materialized: "table"

