WITH base AS (
    SELECT * FROM {{source('slickride', 'RAW_RIDE_UPDATES')}}
)
, cleansed AS (
    SELECT 
        CAST(SYSTEM_RECORD_ID AS STRING) AS SYSTEM_RECORD_ID,
        CAST(RIDE_ID AS STRING) AS RIDE_ID,
        CAST(PASSENGER_NAME AS STRING) AS PASSENGER_NAME,
        CAST(UPDATED_AT AS TIMESTAMP) AS UPDATED_AT,
        CAST(RIDE_STATUS AS STRING) AS RIDE_STATUS,
        CAST(FARE_AMOUNT AS NUMBER) AS FARE_AMOUNT
    FROM base 
)
SELECT * FROM cleansed